/**
 * 学習コンテンツの実データ。
 *
 * 制作方針は docs/content-spec.md、追加手順は /add-content スキルを参照。
 * ここを直接編集する前に `src/content/CLAUDE.md` を読むこと。
 *
 * 原稿は docs/会話文集.md(v0.2)、漢字の選定と樹の枝は docs/対象漢字リスト.md。
 */

import type { ContentSet, KanjiEntry, Sentence, Word } from './types';

/**
 * ID を名前付きの表で持つのは、参照の取り違えを目で見て気づけるようにするため。
 * 生の ULID を各所に直書きすると `newKanjiId` と `kanjiId` の付け間違いが読み取れない。
 * 値そのものは採番済みの ULID で、絶対規則2(主キーは ULID)を満たす。
 *
 * キー名を訓読みではなく `illustrationKey` と同じ英語スラッグにしているのは、
 * 訓読みだと 日/火 がどちらも `hi`、木/聞 がどちらも `ki` になり、章が増えたときに
 * 改名が要るため(docs/対象漢字リスト.md)。
 */
const K = {
  person: '01M16PRDSP9Y398RVZSYAGHXBE',
  big: '01M16PRDSP9Y398RVZSYAGHXBF',
  small: '01M16PRDSQB9SE97E8CZ16VF1K',
  day: '01M16PRDSQB9SE97E8CZ16VF1M',
  eat: '01M16PRDSRPZ6X9PYRP7EK8S1Q',
  above: '01M16PRDSRPZ6X9PYRP7EK8S1R',
  below: '01M16PRDSRPZ6X9PYRP7EK8S1S',
  inside: '01M16PRDSRPZ6X9PYRP7EK8S1T',
  see: '01M16PRDSRPZ6X9PYRP7EK8S1V',
  house: '01M16PRDSRPZ6X9PYRP7EK8S1W',
} as const;

const S = {
  s1: '01M16PRDSRPZ6X9PYRP7EK8S1X',
  s2: '01M16PRDSRPZ6X9PYRP7EK8S1Y',
  s3: '01M16PRDSSKB85MK173DVJY68Z',
  s4: '01M16PRDSSKB85MK173DVJY690',
  s5: '01M16PRDSV2K10ENV4AFEQ8A7Z',
  s6: '01M16PRDSWC4E8ZTQJFSQA15PY',
  s7: '01M16PRDSWC4E8ZTQJFSQA15PZ',
  s8: '01M16PRDSWC4E8ZTQJFSQA15Q0',
  s9: '01M16PRDSWC4E8ZTQJFSQA15Q1',
  s10: '01M16PRDSWC4E8ZTQJFSQA15Q2',
} as const;

/** 対象漢字50字(docs/対象漢字リスト.md)。第1章の10字ぶんを取り込み済み */
export const kanji: KanjiEntry[] = [
  {
    id: K.person,
    character: '人',
    meaning: 'person',
    order: 1,
    chapter: 1,
    illustrationKey: 'person',
    readings: [
      { kana: 'ひと', romaji: 'hito', type: 'kun' },
      { kana: 'にん', romaji: 'nin', type: 'on' },
      { kana: 'じん', romaji: 'jin', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.big,
    character: '大',
    meaning: 'big, large',
    order: 2,
    chapter: 1,
    illustrationKey: 'big',
    readings: [
      { kana: 'おお', romaji: 'ō', type: 'kun' },
      { kana: 'だい', romaji: 'dai', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.small,
    character: '小',
    meaning: 'small',
    order: 3,
    chapter: 1,
    illustrationKey: 'small',
    readings: [
      { kana: 'ちい', romaji: 'chii', type: 'kun' },
      { kana: 'しょう', romaji: 'shō', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.day,
    character: '日',
    meaning: 'day, sun',
    order: 4,
    chapter: 1,
    illustrationKey: 'day',
    readings: [
      { kana: 'ひ', romaji: 'hi', type: 'kun' },
      { kana: 'にち', romaji: 'nichi', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.eat,
    character: '食',
    meaning: 'to eat',
    order: 5,
    chapter: 1,
    illustrationKey: 'eat',
    readings: [
      { kana: 'た', romaji: 'ta', type: 'kun' },
      { kana: 'しょく', romaji: 'shoku', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.above,
    character: '上',
    meaning: 'above, up',
    order: 6,
    chapter: 1,
    illustrationKey: 'above',
    readings: [
      { kana: 'うえ', romaji: 'ue', type: 'kun' },
      { kana: 'じょう', romaji: 'jō', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.below,
    character: '下',
    meaning: 'below, down',
    order: 7,
    chapter: 1,
    illustrationKey: 'below',
    readings: [
      { kana: 'した', romaji: 'shita', type: 'kun' },
      { kana: 'か', romaji: 'ka', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.inside,
    character: '中',
    meaning: 'inside, middle',
    order: 8,
    chapter: 1,
    illustrationKey: 'inside',
    readings: [
      { kana: 'なか', romaji: 'naka', type: 'kun' },
      { kana: 'ちゅう', romaji: 'chū', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.see,
    character: '見',
    meaning: 'to see, to look',
    order: 9,
    chapter: 1,
    illustrationKey: 'see',
    readings: [
      { kana: 'み', romaji: 'mi', type: 'kun' },
      { kana: 'けん', romaji: 'ken', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.house,
    character: '家',
    meaning: 'house, home',
    order: 10,
    chapter: 1,
    illustrationKey: 'house',
    readings: [
      { kana: 'いえ', romaji: 'ie', type: 'kun' },
      { kana: 'か', romaji: 'ka', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
];

/**
 * 漢字の樹の葉になる単語。枝の構成は docs/対象漢字リスト.md の「樹の枝(想定)」に従う。
 *
 * `encounteredInSentenceId` はその語に**出会った回**であって、字が出てくる回ではない。
 * 未出会いの語は null のまま入れておき、灰色のつぼみとして樹に見せる(要件定義書 4.5)。
 */
export const words: Word[] = [
  // 人
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q3',
    kanjiId: K.person,
    surface: '人',
    kana: 'ひと',
    meaning: 'person',
    readingType: 'kun',
    encounteredInSentenceId: S.s1,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q4',
    kanjiId: K.person,
    surface: '三人',
    kana: 'さんにん',
    meaning: 'three people',
    readingType: 'on',
    encounteredInSentenceId: S.s1,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q5',
    kanjiId: K.person,
    surface: '外国人',
    kana: 'がいこくじん',
    meaning: 'foreigner',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 大
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q6',
    kanjiId: K.big,
    surface: '大きい',
    kana: 'おおきい',
    meaning: 'big',
    readingType: 'kun',
    encounteredInSentenceId: S.s2,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q7',
    kanjiId: K.big,
    surface: '大学',
    kana: 'だいがく',
    meaning: 'university',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 小
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q9',
    kanjiId: K.small,
    surface: '小さい',
    kana: 'ちいさい',
    meaning: 'small',
    readingType: 'kun',
    encounteredInSentenceId: S.s3,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV3',
    kanjiId: K.small,
    surface: '小学校',
    kana: 'しょうがっこう',
    meaning: 'elementary school',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 日
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV4',
    kanjiId: K.day,
    surface: '日',
    kana: 'ひ',
    meaning: 'day',
    readingType: 'kun',
    encounteredInSentenceId: S.s4,
  },
  {
    id: '01M16TV3ZESXNE8SXNV0XPYQEP',
    kanjiId: K.day,
    surface: '日曜日',
    kana: 'にちようび',
    meaning: 'Sunday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV6',
    kanjiId: K.day,
    surface: '毎日',
    kana: 'まいにち',
    meaning: 'every day',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 食
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV7',
    kanjiId: K.eat,
    surface: '食べる',
    kana: 'たべる',
    meaning: 'to eat',
    readingType: 'kun',
    encounteredInSentenceId: S.s5,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV8',
    kanjiId: K.eat,
    surface: '食事',
    kana: 'しょくじ',
    meaning: 'meal',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV9',
    kanjiId: K.eat,
    surface: '食堂',
    kana: 'しょくどう',
    meaning: 'dining hall',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 上
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVA',
    kanjiId: K.above,
    surface: '上',
    kana: 'うえ',
    meaning: 'above, on top',
    readingType: 'kun',
    encounteredInSentenceId: S.s6,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVB',
    kanjiId: K.above,
    surface: '上げる',
    kana: 'あげる',
    meaning: 'to raise',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVC',
    kanjiId: K.above,
    surface: '上手',
    kana: 'じょうず',
    meaning: 'good at something',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 下
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVD',
    kanjiId: K.below,
    surface: '下',
    kana: 'した',
    meaning: 'below, under',
    readingType: 'kun',
    encounteredInSentenceId: S.s7,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVE',
    kanjiId: K.below,
    surface: '下げる',
    kana: 'さげる',
    meaning: 'to lower',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVF',
    kanjiId: K.below,
    surface: '地下',
    kana: 'ちか',
    meaning: 'underground',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 中
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVG',
    kanjiId: K.inside,
    surface: '中',
    kana: 'なか',
    meaning: 'inside',
    readingType: 'kun',
    encounteredInSentenceId: S.s8,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVH',
    kanjiId: K.inside,
    surface: '中国',
    kana: 'ちゅうごく',
    meaning: 'China',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVJ',
    kanjiId: K.inside,
    surface: '中学校',
    kana: 'ちゅうがっこう',
    meaning: 'junior high school',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 見
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVK',
    kanjiId: K.see,
    surface: '見る',
    kana: 'みる',
    meaning: 'to see, to look',
    readingType: 'kun',
    encounteredInSentenceId: S.s9,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVM',
    kanjiId: K.see,
    surface: '見せる',
    kana: 'みせる',
    meaning: 'to show',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVN',
    kanjiId: K.see,
    surface: '見学',
    kana: 'けんがく',
    meaning: 'study visit',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 家
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVP',
    kanjiId: K.house,
    surface: '家',
    kana: 'いえ',
    meaning: 'house',
    readingType: 'kun',
    encounteredInSentenceId: S.s10,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVQ',
    kanjiId: K.house,
    surface: '家族',
    kana: 'かぞく',
    meaning: 'family',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVR',
    kanjiId: K.house,
    surface: '家事',
    kana: 'かじ',
    meaning: 'housework',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
];

/**
 * 会話文58文(第1章10 / 第2章15 / 第3章16 / 第4章17)。
 *
 * 第1章は第2段階の演出を一切置かない(決定事項 5章)ため `reencounters` は全て空。
 */
export const sentences: Sentence[] = [
  {
    id: S.s1,
    chapter: 1,
    order: 1,
    scene: '玄関',
    lines: [
      {
        speaker: 'grandma',
        japanese: 'いらっしゃい。長い旅だったねえ。',
        segments: [
          { text: 'いらっしゃい。' },
          { text: '長', reading: 'なが' },
          { text: 'い' },
          { text: '旅', reading: 'たび' },
          { text: 'だったねえ。' },
        ],
        romaji: 'Irasshai. Nagai tabi datta nē.',
        english: 'Welcome. That was a long trip.',
      },
      {
        speaker: 'mia',
        japanese: 'はじめまして。この家は、何人ですか？',
        segments: [
          { text: 'はじめまして。この' },
          { text: '家', reading: 'いえ' },
          { text: 'は、' },
          { text: '何', reading: 'なん' },
          { text: '人', reading: 'にん' },
          { text: 'ですか？' },
        ],
        romaji: 'Hajimemashite. Kono ie wa, nannin desu ka?',
        english: 'Nice to meet you. How many people live in this house?',
      },
      {
        speaker: 'grandma',
        japanese: 'あたしと空がいるから、あなたで三人だねえ。',
        segments: [
          { text: 'あたしと' },
          { text: '空', reading: 'そら' },
          { text: 'がいるから、あなたで' },
          { text: '三', reading: 'さん' },
          { text: '人', reading: 'にん' },
          { text: 'だねえ。' },
        ],
        romaji: 'Atashi to Sora ga iru kara, anata de sannin da nē.',
        english: "There's me and Sora, so you make three.",
      },
      {
        speaker: 'mia',
        japanese: '空は、どんな人ですか？',
        segments: [
          { text: '空', reading: 'そら' },
          { text: 'は、どんな' },
          { text: '人', reading: 'ひと' },
          { text: 'ですか？' },
        ],
        romaji: 'Sora wa, donna hito desu ka?',
        english: 'What kind of person is Sora?',
      },
      {
        speaker: 'grandma',
        japanese: 'ああ、空は猫だよ。',
        segments: [
          { text: 'ああ、' },
          { text: '空', reading: 'そら' },
          { text: 'は' },
          { text: '猫', reading: 'ねこ' },
          { text: 'だよ。' },
        ],
        romaji: 'Ā, Sora wa neko da yo.',
        english: "Oh, Sora's a cat.",
      },
    ],
    newKanjiId: K.person,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s2,
    chapter: 1,
    order: 2,
    scene: '玄関',
    lines: [
      {
        speaker: 'mia',
        japanese: 'すみません、かばんが大きくて…',
        segments: [
          { text: 'すみません、' },
          { text: 'かばんが' },
          { text: '大', reading: 'おお' },
          { text: 'きくて…' },
        ],
        romaji: 'Sumimasen, kaban ga ōkikute...',
        english: 'Excuse me, my bag is so big...',
      },
      {
        speaker: 'grandma',
        japanese: 'いいのいいの。大きい荷物は、そこに置きなさい。',
        segments: [
          { text: 'いいのいいの。' },
          { text: '大', reading: 'おお' },
          { text: 'きい' },
          { text: '荷物', reading: 'にもつ' },
          { text: 'は、そこに' },
          { text: '置', reading: 'お' },
          { text: 'きなさい。' },
        ],
        romaji: 'Ii no ii no. Ōkii nimotsu wa, soko ni okinasai.',
        english: "It's fine, it's fine. Put the big luggage over there.",
      },
    ],
    newKanjiId: K.big,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s3,
    chapter: 1,
    order: 3,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: '空は、小さいですね。',
        segments: [
          { text: '空', reading: 'そら' },
          { text: 'は、' },
          { text: '小', reading: 'ちい' },
          { text: 'さいですね。' },
        ],
        romaji: 'Sora wa, chiisai desu ne.',
        english: 'Sora is small.',
      },
      {
        speaker: 'grandma',
        japanese: 'まだ子猫だからねえ。小さいけど、よく食べるよ。',
        segments: [
          { text: 'まだ' },
          { text: '子猫', reading: 'こねこ' },
          { text: 'だからねえ。' },
          { text: '小', reading: 'ちい' },
          { text: 'さいけど、よく' },
          { text: '食', reading: 'た' },
          { text: 'べるよ。' },
        ],
        romaji: 'Mada koneko dakara nē. Chiisai kedo, yoku taberu yo.',
        english: "He's still a kitten. Small, but he eats a lot.",
      },
    ],
    newKanjiId: K.small,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s4,
    chapter: 1,
    order: 4,
    scene: '縁側',
    lines: [
      {
        speaker: 'mia',
        japanese: '今日は、いい天気ですね。',
        segments: [
          { text: '今日', reading: 'きょう' },
          { text: 'は、いい' },
          { text: '天気', reading: 'てんき' },
          { text: 'ですね。' },
        ],
        romaji: 'Kyō wa, ii tenki desu ne.',
        english: 'The weather is nice today.',
      },
      {
        speaker: 'grandma',
        japanese: 'そうだねえ。こういう日は、ふとんを干そうかね。',
        segments: [
          { text: 'そうだねえ。' },
          { text: 'こういう' },
          { text: '日', reading: 'ひ' },
          { text: 'は、ふとんを' },
          { text: '干', reading: 'ほ' },
          { text: 'そうかね。' },
        ],
        romaji: 'Sō da nē. Kō iu hi wa, futon o hosō ka ne.',
        english: "It certainly is. On days like this, I think I'll air out the futons.",
      },
    ],
    newKanjiId: K.day,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s5,
    chapter: 1,
    order: 5,
    scene: '台所',
    lines: [
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: 'え、さっきも食べたよね？',
        segments: [{ text: 'え、さっきも' }, { text: '食', reading: 'た' }, { text: 'べたよね？' }],
        romaji: 'E, sakki mo tabeta yo ne?',
        english: "Huh? You just ate, didn't you?",
      },
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: '……分かった。おばあちゃん、空がまた食べたいそうです。',
        segments: [
          { text: '……' },
          { text: '分', reading: 'わ' },
          { text: 'かった。' },
          { text: 'おばあちゃん、' },
          { text: '空', reading: 'そら' },
          { text: 'がまた' },
          { text: '食', reading: 'た' },
          { text: 'べたいそうです。' },
        ],
        romaji: '...Wakatta. Obāchan, Sora ga mata tabetai sō desu.',
        english: '...Fine. Grandma, Sora says he wants to eat again.',
      },
    ],
    newKanjiId: K.eat,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s6,
    chapter: 1,
    order: 6,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'あっ、また棚の上にいる。そこ、あぶないよ。',
        segments: [
          { text: 'あっ、また' },
          { text: '棚', reading: 'たな' },
          { text: 'の' },
          { text: '上', reading: 'うえ' },
          { text: 'にいる。' },
          { text: 'そこ、あぶないよ。' },
        ],
        romaji: 'A, mata tana no ue ni iru. Soko, abunai yo.',
        english: "Oh, you're on top of the shelf again. That's dangerous.",
      },
      {
        speaker: 'sora',
        japanese: 'ねむい。',
        segments: [{ text: 'ねむい。' }],
        romaji: 'Nemui.',
        english: 'Sleepy.',
      },
      {
        speaker: 'mia',
        japanese: '聞いてないな……。おばあちゃん、空がまた上にいます。',
        segments: [
          { text: '聞', reading: 'き' },
          { text: 'いてないな……。' },
          { text: 'おばあちゃん、' },
          { text: '空', reading: 'そら' },
          { text: 'がまた' },
          { text: '上', reading: 'うえ' },
          { text: 'にいます。' },
        ],
        romaji: 'Kiitenai na... Obāchan, Sora ga mata ue ni imasu.',
        english: "You're not listening... Grandma, Sora is up there again.",
      },
      {
        speaker: 'grandma',
        japanese: 'ほっときなさい。あの子は上が好きなんだよ。',
        segments: [
          { text: 'ほっときなさい。' },
          { text: 'あの' },
          { text: '子', reading: 'こ' },
          { text: 'は' },
          { text: '上', reading: 'うえ' },
          { text: 'が' },
          { text: '好', reading: 'す' },
          { text: 'きなんだよ。' },
        ],
        romaji: 'Hottokinasai. Ano ko wa ue ga suki nan da yo.',
        english: 'Just leave him. That one loves high places.',
      },
    ],
    newKanjiId: K.above,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s7,
    chapter: 1,
    order: 7,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'メガネが、ありません。',
        segments: [{ text: 'メガネが、' }, { text: 'ありません。' }],
        romaji: 'Megane ga, arimasen.',
        english: "I can't find my glasses.",
      },
      {
        speaker: 'grandma',
        japanese: '机の下は見たかい？下によく落ちてるんだよ。',
        segments: [
          { text: '机', reading: 'つくえ' },
          { text: 'の' },
          { text: '下', reading: 'した' },
          { text: 'は' },
          { text: '見', reading: 'み' },
          { text: 'たかい？' },
          { text: '下', reading: 'した' },
          { text: 'によく' },
          { text: '落', reading: 'お' },
          { text: 'ちてるんだよ。' },
        ],
        romaji: 'Tsukue no shita wa mita kai? Shita ni yoku ochiterun da yo.',
        english: "Did you look under the desk? They're often down there.",
      },
    ],
    newKanjiId: K.below,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s8,
    chapter: 1,
    order: 8,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        japanese: 'この箱の中は、何ですか？',
        segments: [
          { text: 'この' },
          { text: '箱', reading: 'はこ' },
          { text: 'の' },
          { text: '中', reading: 'なか' },
          { text: 'は、' },
          { text: '何', reading: 'なん' },
          { text: 'ですか？' },
        ],
        romaji: 'Kono hako no naka wa, nan desu ka?',
        english: "What's inside this box?",
      },
      {
        speaker: 'grandma',
        japanese: 'せんべいだよ。中のものは、好きに食べていいからね。',
        segments: [
          { text: 'せんべいだよ。' },
          { text: '中', reading: 'なか' },
          { text: 'のものは、' },
          { text: '好', reading: 'す' },
          { text: 'きに' },
          { text: '食', reading: 'た' },
          { text: 'べていいからね。' },
        ],
        romaji: 'Sembei da yo. Naka no mono wa, suki ni tabete ii kara ne.',
        english: 'Rice crackers. Feel free to eat anything inside.',
      },
    ],
    newKanjiId: K.inside,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s9,
    chapter: 1,
    order: 9,
    scene: '縁側',
    lines: [
      {
        speaker: 'grandma',
        japanese: 'ミアちゃん、ちょっと来てごらん。',
        segments: [
          { text: 'ミアちゃん、' },
          { text: 'ちょっと' },
          { text: '来', reading: 'き' },
          { text: 'てごらん。' },
        ],
        romaji: 'Mia-chan, chotto kite goran.',
        english: 'Mia, come here for a moment.',
      },
      {
        speaker: 'mia',
        japanese: 'わあ、星がきれいですね。',
        segments: [
          { text: 'わあ、' },
          { text: '星', reading: 'ほし' },
          { text: 'がきれいですね。' },
        ],
        romaji: 'Wā, hoshi ga kirei desu ne.',
        english: 'Wow, the stars are beautiful.',
      },
      {
        speaker: 'grandma',
        japanese: 'たまには、こうやって見るのもいいだろう？',
        segments: [
          { text: 'たまには、' },
          { text: 'こうやって' },
          { text: '見', reading: 'み' },
          { text: 'るのもいいだろう？' },
        ],
        romaji: 'Tama ni wa, kō yatte miru no mo ii darō?',
        english: "It's nice to look up like this once in a while, isn't it?",
      },
    ],
    newKanjiId: K.see,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s10,
    chapter: 1,
    order: 10,
    scene: '玄関',
    lines: [
      {
        speaker: 'mia',
        japanese: 'ただいま。',
        segments: [{ text: 'ただいま。' }],
        romaji: 'Tadaima.',
        english: "I'm home.",
      },
      {
        speaker: 'grandma',
        japanese: 'おかえり。この家にも、もう慣れたかい？',
        segments: [
          { text: 'おかえり。' },
          { text: 'この' },
          { text: '家', reading: 'いえ' },
          { text: 'にも、もう' },
          { text: '慣', reading: 'な' },
          { text: 'れたかい？' },
        ],
        romaji: 'Okaeri. Kono ie ni mo, mō nareta kai?',
        english: 'Welcome back. Are you getting used to this house?',
      },
      {
        speaker: 'mia',
        japanese: 'はい。家が、あたたかいです。',
        segments: [
          { text: 'はい。' },
          { text: '家', reading: 'いえ' },
          { text: 'が、あたたかいです。' },
        ],
        romaji: 'Hai. Ie ga, atatakai desu.',
        english: 'Yes. The house feels warm.',
      },
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: '……おかえりは？',
        segments: [{ text: '……おかえりは？' }],
        romaji: '...Okaeri wa?',
        english: "...What about 'welcome back'?",
      },
    ],
    newKanjiId: K.house,
    reencounters: [],
    isFree: true,
  },
];

export const contentSet: ContentSet = { kanji, words, sentences };
