/**
 * 学習コンテンツの実データ。
 *
 * 制作方針は docs/content-spec.md、追加手順は /add-content スキルを参照。
 * ここを直接編集する前に `src/content/CLAUDE.md` を読むこと。
 *
 * 原稿は docs/会話文集.md(v0.2)、漢字の選定と樹の枝は docs/対象漢字リスト.md。
 */

import type { ContentSet, KanjiEntry, Sentence, Word } from './types';

/**
 * ID を名前付きの表で持つのは、参照の取り違えを目で見て気づけるようにするため。
 * 生の ULID を各所に直書きすると `newKanjiId` と `kanjiId` の付け間違いが読み取れない。
 * 値そのものは採番済みの ULID で、絶対規則2(主キーは ULID)を満たす。
 *
 * キー名を訓読みではなく `illustrationKey` と同じ英語スラッグにしているのは、
 * 訓読みだと 日/火 がどちらも `hi`、木/聞 がどちらも `ki` になり、章が増えたときに
 * 改名が要るため(docs/対象漢字リスト.md)。
 */
const K = {
  person: '01M16PRDSP9Y398RVZSYAGHXBE',
  big: '01M16PRDSP9Y398RVZSYAGHXBF',
  small: '01M16PRDSQB9SE97E8CZ16VF1K',
  day: '01M16PRDSQB9SE97E8CZ16VF1M',
  eat: '01M16PRDSRPZ6X9PYRP7EK8S1Q',
  above: '01M16PRDSRPZ6X9PYRP7EK8S1R',
  below: '01M16PRDSRPZ6X9PYRP7EK8S1S',
  inside: '01M16PRDSRPZ6X9PYRP7EK8S1T',
  see: '01M16PRDSRPZ6X9PYRP7EK8S1V',
  house: '01M16PRDSRPZ6X9PYRP7EK8S1W',
  // 第2章。順序は docs/会話文集.md の出題順に従う(docs/対象漢字リスト.md は 2026-08-30 に追従済み)
  early: '01M18GY6KZZF4H3S0DZTGF7X0M',
  time: '01M18GY6M0GRZE63GYQYGNCAF9',
  interval: '01M18GY6M0GRZE63GYQYGNCAFA',
  understand: '01M18GY6M1AJSPBJA2SAWDJ274',
  heaven: '01M18GY6M1AJSPBJA2SAWDJ275',
  rain: '01M18GY6M1AJSPBJA2SAWDJ276',
  moon: '01M18K0X136KYE9NT0E2SN0Y4E',
  water: '01M18K0X140ZPY8KMJ1QXNT9BF',
  fire: '01M18K0X140ZPY8KMJ1QXNT9BG',
  tree: '01M18K0X156J3SJ9H7WT4DPVB9',
  money: '01M18K0X156J3SJ9H7WT4DPVBA',
  soil: '01M18K0X156J3SJ9H7WT4DPVBB',
  rest: '01M18K0X156J3SJ9H7WT4DPVBC',
  speak: '01M18K0X16PZH4HCKFQ52VZKM0',
} as const;

const S = {
  s1: '01M16PRDSRPZ6X9PYRP7EK8S1X',
  s2: '01M16PRDSRPZ6X9PYRP7EK8S1Y',
  s3: '01M16PRDSSKB85MK173DVJY68Z',
  s4: '01M16PRDSSKB85MK173DVJY690',
  s5: '01M16PRDSV2K10ENV4AFEQ8A7Z',
  s6: '01M16PRDSWC4E8ZTQJFSQA15PY',
  s7: '01M16PRDSWC4E8ZTQJFSQA15PZ',
  s8: '01M16PRDSWC4E8ZTQJFSQA15Q0',
  s9: '01M16PRDSWC4E8ZTQJFSQA15Q1',
  s10: '01M16PRDSWC4E8ZTQJFSQA15Q2',
  s11: '01M18GY6M4VRVD7BXGZAFP1GC3',
  s12: '01M18GY6M4VRVD7BXGZAFP1GC4',
  s13: '01M18GY6M4VRVD7BXGZAFP1GC5',
  s14: '01M18GY6M4VRVD7BXGZAFP1GC6',
  s15: '01M18GY6M4VRVD7BXGZAFP1GC7',
  s16: '01M18GY6M4VRVD7BXGZAFP1GC8',
  s17: '01M18GY6M4VRVD7BXGZAFP1GC9',
  s18: '01M18GY6M4VRVD7BXGZAFP1GCA',
  s19: '01M18GY6M4VRVD7BXGZAFP1GCB',
  s20: '01M18GY6M4VRVD7BXGZAFP1GCC',
  s21: '01M18GY6M4VRVD7BXGZAFP1GCD',
  s22: '01M18GY6M4VRVD7BXGZAFP1GCE',
  s23: '01M18GY6M4VRVD7BXGZAFP1GCF',
  s24: '01M18GY6M4VRVD7BXGZAFP1GCG',
  s25: '01M18GY6M4VRVD7BXGZAFP1GCH',
} as const;

/** 対象漢字50字(docs/対象漢字リスト.md)。第1章の10字ぶんを取り込み済み */
export const kanji: KanjiEntry[] = [
  {
    id: K.person,
    character: '人',
    meaning: 'person',
    order: 1,
    chapter: 1,
    illustrationKey: 'person',
    readings: [
      { kana: 'ひと', romaji: 'hito', type: 'kun' },
      { kana: 'にん', romaji: 'nin', type: 'on' },
      { kana: 'じん', romaji: 'jin', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.big,
    character: '大',
    meaning: 'big, large',
    order: 2,
    chapter: 1,
    illustrationKey: 'big',
    readings: [
      { kana: 'おお', romaji: 'ō', type: 'kun' },
      { kana: 'だい', romaji: 'dai', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.small,
    character: '小',
    meaning: 'small',
    order: 3,
    chapter: 1,
    illustrationKey: 'small',
    readings: [
      { kana: 'ちい', romaji: 'chii', type: 'kun' },
      { kana: 'しょう', romaji: 'shō', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.day,
    character: '日',
    meaning: 'day, sun',
    order: 4,
    chapter: 1,
    illustrationKey: 'day',
    readings: [
      { kana: 'ひ', romaji: 'hi', type: 'kun' },
      { kana: 'にち', romaji: 'nichi', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.eat,
    character: '食',
    meaning: 'to eat',
    order: 5,
    chapter: 1,
    illustrationKey: 'eat',
    readings: [
      { kana: 'た', romaji: 'ta', type: 'kun' },
      { kana: 'しょく', romaji: 'shoku', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.above,
    character: '上',
    meaning: 'above, up',
    order: 6,
    chapter: 1,
    illustrationKey: 'above',
    readings: [
      { kana: 'うえ', romaji: 'ue', type: 'kun' },
      { kana: 'じょう', romaji: 'jō', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.below,
    character: '下',
    meaning: 'below, down',
    order: 7,
    chapter: 1,
    illustrationKey: 'below',
    readings: [
      { kana: 'した', romaji: 'shita', type: 'kun' },
      { kana: 'か', romaji: 'ka', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.inside,
    character: '中',
    meaning: 'inside, middle',
    order: 8,
    chapter: 1,
    illustrationKey: 'inside',
    readings: [
      { kana: 'なか', romaji: 'naka', type: 'kun' },
      { kana: 'ちゅう', romaji: 'chū', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.see,
    character: '見',
    meaning: 'to see, to look',
    order: 9,
    chapter: 1,
    illustrationKey: 'see',
    readings: [
      { kana: 'み', romaji: 'mi', type: 'kun' },
      { kana: 'けん', romaji: 'ken', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.house,
    character: '家',
    meaning: 'house, home',
    order: 10,
    chapter: 1,
    illustrationKey: 'house',
    readings: [
      { kana: 'いえ', romaji: 'ie', type: 'kun' },
      { kana: 'か', romaji: 'ka', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.early,
    character: '早',
    meaning: 'early',
    order: 11,
    chapter: 2,
    illustrationKey: 'early',
    readings: [
      { kana: 'はや', romaji: 'haya', type: 'kun' },
      { kana: 'そう', romaji: 'sō', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.time,
    character: '時',
    meaning: 'time',
    order: 12,
    chapter: 2,
    illustrationKey: 'time',
    readings: [
      { kana: 'とき', romaji: 'toki', type: 'kun' },
      { kana: 'じ', romaji: 'ji', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.interval,
    character: '間',
    meaning: 'interval, space between',
    order: 13,
    chapter: 2,
    illustrationKey: 'interval',
    readings: [
      { kana: 'あいだ', romaji: 'aida', type: 'kun' },
      { kana: 'かん', romaji: 'kan', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.understand,
    character: '分',
    meaning: 'to understand, to divide',
    order: 14,
    chapter: 2,
    illustrationKey: 'understand',
    readings: [
      { kana: 'わ', romaji: 'wa', type: 'kun' },
      { kana: 'ぶん', romaji: 'bun', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.heaven,
    character: '天',
    meaning: 'heaven, sky',
    order: 15,
    chapter: 2,
    illustrationKey: 'heaven',
    // 例外字。訓読み(あま)がほぼ使われないので音読みで導入し、第2段階の対象にもしない
    // (docs/content-decisions.md 4章 / 決定の記録は会話文集 #15 のメモ)
    readings: [{ kana: 'てん', romaji: 'ten', type: 'on' }],
    readingIntroduction: 'on-only',
  },
  {
    id: K.rain,
    character: '雨',
    meaning: 'rain',
    order: 16,
    chapter: 2,
    illustrationKey: 'rain',
    readings: [
      { kana: 'あめ', romaji: 'ame', type: 'kun' },
      { kana: 'う', romaji: 'u', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.moon,
    character: '月',
    meaning: 'moon, month',
    order: 17,
    chapter: 2,
    illustrationKey: 'moon',
    readings: [
      { kana: 'つき', romaji: 'tsuki', type: 'kun' },
      { kana: 'げつ', romaji: 'getsu', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.water,
    character: '水',
    meaning: 'water',
    order: 18,
    chapter: 2,
    illustrationKey: 'water',
    readings: [
      { kana: 'みず', romaji: 'mizu', type: 'kun' },
      { kana: 'すい', romaji: 'sui', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.fire,
    character: '火',
    meaning: 'fire',
    order: 19,
    chapter: 2,
    illustrationKey: 'fire',
    readings: [
      { kana: 'ひ', romaji: 'hi', type: 'kun' },
      { kana: 'か', romaji: 'ka', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.tree,
    character: '木',
    meaning: 'tree, wood',
    order: 20,
    chapter: 2,
    illustrationKey: 'tree',
    readings: [
      { kana: 'き', romaji: 'ki', type: 'kun' },
      { kana: 'もく', romaji: 'moku', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.money,
    character: '金',
    meaning: 'money, gold',
    order: 21,
    chapter: 2,
    illustrationKey: 'money',
    readings: [
      { kana: 'かね', romaji: 'kane', type: 'kun' },
      { kana: 'きん', romaji: 'kin', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.soil,
    character: '土',
    meaning: 'soil, earth',
    order: 22,
    chapter: 2,
    illustrationKey: 'soil',
    readings: [
      { kana: 'つち', romaji: 'tsuchi', type: 'kun' },
      { kana: 'ど', romaji: 'do', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.rest,
    character: '休',
    meaning: 'to rest',
    order: 23,
    chapter: 2,
    illustrationKey: 'rest',
    readings: [
      { kana: 'やす', romaji: 'yasu', type: 'kun' },
      { kana: 'きゅう', romaji: 'kyū', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
  {
    id: K.speak,
    character: '話',
    meaning: 'to speak',
    order: 24,
    chapter: 2,
    illustrationKey: 'speak',
    readings: [
      { kana: 'はな', romaji: 'hana', type: 'kun' },
      { kana: 'わ', romaji: 'wa', type: 'on' },
    ],
    readingIntroduction: 'kun-first',
  },
];

/**
 * 漢字の樹の葉になる単語。枝の構成は docs/対象漢字リスト.md の「樹の枝(想定)」に従う。
 *
 * `encounteredInSentenceId` はその語に**出会った回**であって、字が出てくる回ではない。
 * 未出会いの語は null のまま入れておき、灰色のつぼみとして樹に見せる(要件定義書 4.5)。
 */
export const words: Word[] = [
  // 人
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q3',
    kanjiId: K.person,
    surface: '人',
    kana: 'ひと',
    meaning: 'person',
    readingType: 'kun',
    encounteredInSentenceId: S.s1,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q4',
    kanjiId: K.person,
    surface: '三人',
    kana: 'さんにん',
    meaning: 'three people',
    readingType: 'on',
    encounteredInSentenceId: S.s1,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q5',
    kanjiId: K.person,
    surface: '外国人',
    kana: 'がいこくじん',
    meaning: 'foreigner',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 大
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q6',
    kanjiId: K.big,
    surface: '大きい',
    kana: 'おおきい',
    meaning: 'big',
    readingType: 'kun',
    encounteredInSentenceId: S.s2,
  },
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q7',
    kanjiId: K.big,
    surface: '大学',
    kana: 'だいがく',
    meaning: 'university',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 小
  {
    id: '01M16PRDSWC4E8ZTQJFSQA15Q9',
    kanjiId: K.small,
    surface: '小さい',
    kana: 'ちいさい',
    meaning: 'small',
    readingType: 'kun',
    encounteredInSentenceId: S.s3,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV3',
    kanjiId: K.small,
    surface: '小学校',
    kana: 'しょうがっこう',
    meaning: 'elementary school',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 日
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV4',
    kanjiId: K.day,
    surface: '日',
    kana: 'ひ',
    meaning: 'day',
    readingType: 'kun',
    encounteredInSentenceId: S.s4,
  },
  {
    id: '01M16TV3ZESXNE8SXNV0XPYQEP',
    kanjiId: K.day,
    surface: '日曜日',
    kana: 'にちようび',
    meaning: 'Sunday',
    readingType: 'on',
    // #17 がこの語を提示する第2段階の回。演出で読みを見せた直後に
    // 樹ではつぼみのまま、という逆転が起きないようにする
    encounteredInSentenceId: S.s17,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV6',
    kanjiId: K.day,
    surface: '毎日',
    kana: 'まいにち',
    meaning: 'every day',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 食
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV7',
    kanjiId: K.eat,
    surface: '食べる',
    kana: 'たべる',
    meaning: 'to eat',
    readingType: 'kun',
    encounteredInSentenceId: S.s5,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV8',
    kanjiId: K.eat,
    surface: '食事',
    kana: 'しょくじ',
    meaning: 'meal',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTV9',
    kanjiId: K.eat,
    surface: '食堂',
    kana: 'しょくどう',
    meaning: 'dining hall',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 上
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVA',
    kanjiId: K.above,
    surface: '上',
    kana: 'うえ',
    meaning: 'above, on top',
    readingType: 'kun',
    encounteredInSentenceId: S.s6,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVB',
    kanjiId: K.above,
    surface: '上げる',
    kana: 'あげる',
    meaning: 'to raise',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVC',
    kanjiId: K.above,
    surface: '上手',
    kana: 'じょうず',
    meaning: 'good at something',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 下
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVD',
    kanjiId: K.below,
    surface: '下',
    kana: 'した',
    meaning: 'below, under',
    readingType: 'kun',
    encounteredInSentenceId: S.s7,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVE',
    kanjiId: K.below,
    surface: '下げる',
    kana: 'さげる',
    meaning: 'to lower',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVF',
    kanjiId: K.below,
    surface: '地下',
    kana: 'ちか',
    meaning: 'underground',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 中
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVG',
    kanjiId: K.inside,
    surface: '中',
    kana: 'なか',
    meaning: 'inside',
    readingType: 'kun',
    encounteredInSentenceId: S.s8,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVH',
    kanjiId: K.inside,
    surface: '中国',
    kana: 'ちゅうごく',
    meaning: 'China',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVJ',
    kanjiId: K.inside,
    surface: '中学校',
    kana: 'ちゅうがっこう',
    meaning: 'junior high school',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 見
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVK',
    kanjiId: K.see,
    surface: '見る',
    kana: 'みる',
    meaning: 'to see, to look',
    readingType: 'kun',
    encounteredInSentenceId: S.s9,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVM',
    kanjiId: K.see,
    surface: '見せる',
    kana: 'みせる',
    meaning: 'to show',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVN',
    kanjiId: K.see,
    surface: '見学',
    kana: 'けんがく',
    meaning: 'study visit',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 家
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVP',
    kanjiId: K.house,
    surface: '家',
    kana: 'いえ',
    meaning: 'house',
    readingType: 'kun',
    encounteredInSentenceId: S.s10,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVQ',
    kanjiId: K.house,
    surface: '家族',
    kana: 'かぞく',
    meaning: 'family',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M16PRDSXZEQM8BJJMZZWKTVR',
    kanjiId: K.house,
    surface: '家事',
    kana: 'かじ',
    meaning: 'housework',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 早
  {
    id: '01M18H20BSCTVZMFVPKHYNKT7P',
    kanjiId: K.early,
    surface: '早い',
    kana: 'はやい',
    meaning: 'early',
    readingType: 'kun',
    encounteredInSentenceId: S.s11,
  },
  {
    id: '01M18H20BTWAWN9362NNZ5N9YK',
    kanjiId: K.early,
    surface: '早起き',
    kana: 'はやおき',
    meaning: 'getting up early',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18H20BVTQP4AE75DHZPT0RT',
    kanjiId: K.early,
    surface: '早朝',
    kana: 'そうちょう',
    meaning: 'early morning',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 時
  {
    id: '01M18H20BVTQP4AE75DHZPT0RV',
    kanjiId: K.time,
    surface: '時',
    kana: 'とき',
    meaning: 'time, moment',
    readingType: 'kun',
    encounteredInSentenceId: S.s12,
  },
  {
    id: '01M18H20BVTQP4AE75DHZPT0RW',
    kanjiId: K.time,
    surface: '時間',
    kana: 'じかん',
    meaning: 'time, hour',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 間
  {
    id: '01M18H20BVTQP4AE75DHZPT0RX',
    kanjiId: K.interval,
    surface: '間',
    kana: 'あいだ',
    meaning: 'space between',
    readingType: 'kun',
    encounteredInSentenceId: S.s13,
  },
  {
    id: '01M18H20BVTQP4AE75DHZPT0RY',
    kanjiId: K.interval,
    surface: '時間',
    kana: 'じかん',
    meaning: 'time, hour',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18H20BVTQP4AE75DHZPT0RZ',
    kanjiId: K.interval,
    surface: '人間',
    kana: 'にんげん',
    meaning: 'human being',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 分
  {
    id: '01M18H20BVTQP4AE75DHZPT0S0',
    kanjiId: K.understand,
    surface: '分かる',
    kana: 'わかる',
    meaning: 'to understand',
    readingType: 'kun',
    encounteredInSentenceId: S.s14,
  },
  {
    id: '01M18H20BVTQP4AE75DHZPT0S1',
    kanjiId: K.understand,
    surface: '分ける',
    kana: 'わける',
    meaning: 'to divide',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18H20BWPHMKZA8KWCA7K92F',
    kanjiId: K.understand,
    surface: '自分',
    kana: 'じぶん',
    meaning: 'oneself',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 天(例外字。訓読みを持たないので葉もすべて音読み)
  {
    id: '01M18H20BWPHMKZA8KWCA7K92G',
    kanjiId: K.heaven,
    surface: '天気',
    kana: 'てんき',
    meaning: 'weather',
    readingType: 'on',
    encounteredInSentenceId: S.s15,
  },
  {
    id: '01M18H20BWPHMKZA8KWCA7K92H',
    kanjiId: K.heaven,
    surface: '天国',
    kana: 'てんごく',
    meaning: 'heaven',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 雨
  {
    id: '01M18H20BWPHMKZA8KWCA7K92J',
    kanjiId: K.rain,
    surface: '雨',
    kana: 'あめ',
    meaning: 'rain',
    readingType: 'kun',
    encounteredInSentenceId: S.s16,
  },
  {
    id: '01M18H20BWPHMKZA8KWCA7K92K',
    kanjiId: K.rain,
    surface: '大雨',
    kana: 'おおあめ',
    meaning: 'heavy rain',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18H20BWPHMKZA8KWCA7K92M',
    kanjiId: K.rain,
    surface: '雨天',
    kana: 'うてん',
    meaning: 'rainy weather',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 月
  {
    id: '01M18K0X18TXJ2V55H2JTY2SM7',
    kanjiId: K.moon,
    surface: '月',
    kana: 'つき',
    meaning: 'moon',
    readingType: 'kun',
    encounteredInSentenceId: S.s18,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SM8',
    kanjiId: K.moon,
    surface: '月曜日',
    kana: 'げつようび',
    meaning: 'Monday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SM9',
    kanjiId: K.moon,
    surface: '今月',
    kana: 'こんげつ',
    meaning: 'this month',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 水
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMA',
    kanjiId: K.water,
    surface: '水',
    kana: 'みず',
    meaning: 'water',
    readingType: 'kun',
    encounteredInSentenceId: S.s19,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMB',
    kanjiId: K.water,
    surface: '水曜日',
    kana: 'すいようび',
    meaning: 'Wednesday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMC',
    kanjiId: K.water,
    surface: '水道',
    kana: 'すいどう',
    meaning: 'running water',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 火
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMD',
    kanjiId: K.fire,
    surface: '火',
    kana: 'ひ',
    meaning: 'fire',
    readingType: 'kun',
    encounteredInSentenceId: S.s20,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SME',
    kanjiId: K.fire,
    surface: '火曜日',
    kana: 'かようび',
    meaning: 'Tuesday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMF',
    kanjiId: K.fire,
    surface: '花火',
    kana: 'はなび',
    meaning: 'fireworks',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  // 木
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMG',
    kanjiId: K.tree,
    surface: '木',
    kana: 'き',
    meaning: 'tree',
    readingType: 'kun',
    encounteredInSentenceId: S.s21,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMH',
    kanjiId: K.tree,
    surface: '木曜日',
    kana: 'もくようび',
    meaning: 'Thursday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 金
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMJ',
    kanjiId: K.money,
    surface: 'お金',
    kana: 'おかね',
    meaning: 'money',
    readingType: 'kun',
    encounteredInSentenceId: S.s22,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMK',
    kanjiId: K.money,
    surface: '金曜日',
    kana: 'きんようび',
    meaning: 'Friday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 土
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMM',
    kanjiId: K.soil,
    surface: '土',
    kana: 'つち',
    meaning: 'soil',
    readingType: 'kun',
    encounteredInSentenceId: S.s23,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMN',
    kanjiId: K.soil,
    surface: '土曜日',
    kana: 'どようび',
    meaning: 'Saturday',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 休
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMP',
    kanjiId: K.rest,
    surface: '休む',
    kana: 'やすむ',
    meaning: 'to rest',
    readingType: 'kun',
    encounteredInSentenceId: S.s24,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMQ',
    kanjiId: K.rest,
    surface: '休み',
    kana: 'やすみ',
    meaning: 'break, holiday',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18K0X18TXJ2V55H2JTY2SMR',
    kanjiId: K.rest,
    surface: '休日',
    kana: 'きゅうじつ',
    meaning: 'day off',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
  // 話
  {
    id: '01M18K0X19S4HJ5R7ACZP32QAP',
    kanjiId: K.speak,
    surface: '話す',
    kana: 'はなす',
    meaning: 'to speak',
    readingType: 'kun',
    encounteredInSentenceId: S.s25,
  },
  {
    id: '01M18K0X19S4HJ5R7ACZP32QAQ',
    kanjiId: K.speak,
    surface: '話',
    kana: 'はなし',
    meaning: 'story, talk',
    readingType: 'kun',
    encounteredInSentenceId: null,
  },
  {
    id: '01M18K0X19S4HJ5R7ACZP32QAR',
    kanjiId: K.speak,
    surface: '電話',
    kana: 'でんわ',
    meaning: 'telephone',
    readingType: 'on',
    encounteredInSentenceId: null,
  },
];

/**
 * 会話文58文(第1章10 / 第2章15 / 第3章16 / 第4章17)。
 *
 * 第1章は第2段階の演出を一切置かない(決定事項 5章)ため `reencounters` は全て空。
 */
export const sentences: Sentence[] = [
  {
    id: S.s1,
    chapter: 1,
    order: 1,
    scene: '玄関',
    lines: [
      {
        speaker: 'grandma',
        japanese: 'いらっしゃい。長い旅だったねえ。',
        segments: [
          { text: 'いらっしゃい。' },
          { text: '長', reading: 'なが' },
          { text: 'い' },
          { text: '旅', reading: 'たび' },
          { text: 'だったねえ。' },
        ],
        romaji: 'Irasshai. Nagai tabi datta nē.',
        english: 'Welcome. That was a long trip.',
      },
      {
        speaker: 'mia',
        japanese: 'はじめまして。この家は、何人ですか？',
        segments: [
          { text: 'はじめまして。この' },
          { text: '家', reading: 'いえ' },
          { text: 'は、' },
          { text: '何', reading: 'なん' },
          { text: '人', reading: 'にん' },
          { text: 'ですか？' },
        ],
        romaji: 'Hajimemashite. Kono ie wa, nannin desu ka?',
        english: 'Nice to meet you. How many people live in this house?',
      },
      {
        speaker: 'grandma',
        japanese: 'あたしと空がいるから、あなたで三人だねえ。',
        segments: [
          { text: 'あたしと' },
          { text: '空', reading: 'そら' },
          { text: 'がいるから、あなたで' },
          { text: '三', reading: 'さん' },
          { text: '人', reading: 'にん' },
          { text: 'だねえ。' },
        ],
        romaji: 'Atashi to Sora ga iru kara, anata de sannin da nē.',
        english: "There's me and Sora, so you make three.",
      },
      {
        speaker: 'mia',
        japanese: '空は、どんな人ですか？',
        segments: [
          { text: '空', reading: 'そら' },
          { text: 'は、どんな' },
          { text: '人', reading: 'ひと' },
          { text: 'ですか？' },
        ],
        romaji: 'Sora wa, donna hito desu ka?',
        english: 'What kind of person is Sora?',
      },
      {
        speaker: 'grandma',
        japanese: 'ああ、空は猫だよ。',
        segments: [
          { text: 'ああ、' },
          { text: '空', reading: 'そら' },
          { text: 'は' },
          { text: '猫', reading: 'ねこ' },
          { text: 'だよ。' },
        ],
        romaji: 'Ā, Sora wa neko da yo.',
        english: "Oh, Sora's a cat.",
      },
    ],
    newKanjiId: K.person,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s2,
    chapter: 1,
    order: 2,
    scene: '玄関',
    lines: [
      {
        speaker: 'mia',
        japanese: 'すみません、かばんが大きくて…',
        segments: [
          { text: 'すみません、' },
          { text: 'かばんが' },
          { text: '大', reading: 'おお' },
          { text: 'きくて…' },
        ],
        romaji: 'Sumimasen, kaban ga ōkikute...',
        english: 'Excuse me, my bag is so big...',
      },
      {
        speaker: 'grandma',
        japanese: 'いいのいいの。大きい荷物は、そこに置きなさい。',
        segments: [
          { text: 'いいのいいの。' },
          { text: '大', reading: 'おお' },
          { text: 'きい' },
          { text: '荷物', reading: 'にもつ' },
          { text: 'は、そこに' },
          { text: '置', reading: 'お' },
          { text: 'きなさい。' },
        ],
        romaji: 'Ii no ii no. Ōkii nimotsu wa, soko ni okinasai.',
        english: "It's fine, it's fine. Put the big luggage over there.",
      },
    ],
    newKanjiId: K.big,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s3,
    chapter: 1,
    order: 3,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: '空は、小さいですね。',
        segments: [
          { text: '空', reading: 'そら' },
          { text: 'は、' },
          { text: '小', reading: 'ちい' },
          { text: 'さいですね。' },
        ],
        romaji: 'Sora wa, chiisai desu ne.',
        english: 'Sora is small.',
      },
      {
        speaker: 'grandma',
        japanese: 'まだ子猫だからねえ。小さいけど、よく食べるよ。',
        segments: [
          { text: 'まだ' },
          { text: '子猫', reading: 'こねこ' },
          { text: 'だからねえ。' },
          { text: '小', reading: 'ちい' },
          { text: 'さいけど、よく' },
          { text: '食', reading: 'た' },
          { text: 'べるよ。' },
        ],
        romaji: 'Mada koneko dakara nē. Chiisai kedo, yoku taberu yo.',
        english: "He's still a kitten. Small, but he eats a lot.",
      },
    ],
    newKanjiId: K.small,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s4,
    chapter: 1,
    order: 4,
    scene: '縁側',
    lines: [
      {
        speaker: 'mia',
        japanese: '今日は、いい天気ですね。',
        segments: [
          { text: '今日', reading: 'きょう' },
          { text: 'は、いい' },
          { text: '天気', reading: 'てんき' },
          { text: 'ですね。' },
        ],
        romaji: 'Kyō wa, ii tenki desu ne.',
        english: 'The weather is nice today.',
      },
      {
        speaker: 'grandma',
        japanese: 'そうだねえ。こういう日は、ふとんを干そうかね。',
        segments: [
          { text: 'そうだねえ。' },
          { text: 'こういう' },
          { text: '日', reading: 'ひ' },
          { text: 'は、ふとんを' },
          { text: '干', reading: 'ほ' },
          { text: 'そうかね。' },
        ],
        romaji: 'Sō da nē. Kō iu hi wa, futon o hosō ka ne.',
        english: "It certainly is. On days like this, I think I'll air out the futons.",
      },
    ],
    newKanjiId: K.day,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s5,
    chapter: 1,
    order: 5,
    scene: '台所',
    lines: [
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: 'え、さっきも食べたよね？',
        segments: [{ text: 'え、さっきも' }, { text: '食', reading: 'た' }, { text: 'べたよね？' }],
        romaji: 'E, sakki mo tabeta yo ne?',
        english: "Huh? You just ate, didn't you?",
      },
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: '……分かった。おばあちゃん、空がまた食べたいそうです。',
        segments: [
          { text: '……' },
          { text: '分', reading: 'わ' },
          { text: 'かった。' },
          { text: 'おばあちゃん、' },
          { text: '空', reading: 'そら' },
          { text: 'がまた' },
          { text: '食', reading: 'た' },
          { text: 'べたいそうです。' },
        ],
        romaji: '...Wakatta. Obāchan, Sora ga mata tabetai sō desu.',
        english: '...Fine. Grandma, Sora says he wants to eat again.',
      },
    ],
    newKanjiId: K.eat,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s6,
    chapter: 1,
    order: 6,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'あっ、また棚の上にいる。そこ、あぶないよ。',
        segments: [
          { text: 'あっ、また' },
          { text: '棚', reading: 'たな' },
          { text: 'の' },
          { text: '上', reading: 'うえ' },
          { text: 'にいる。' },
          { text: 'そこ、あぶないよ。' },
        ],
        romaji: 'A, mata tana no ue ni iru. Soko, abunai yo.',
        english: "Oh, you're on top of the shelf again. That's dangerous.",
      },
      {
        speaker: 'sora',
        japanese: 'ねむい。',
        segments: [{ text: 'ねむい。' }],
        romaji: 'Nemui.',
        english: 'Sleepy.',
      },
      {
        speaker: 'mia',
        japanese: '聞いてないな……。おばあちゃん、空がまた上にいます。',
        segments: [
          { text: '聞', reading: 'き' },
          { text: 'いてないな……。' },
          { text: 'おばあちゃん、' },
          { text: '空', reading: 'そら' },
          { text: 'がまた' },
          { text: '上', reading: 'うえ' },
          { text: 'にいます。' },
        ],
        romaji: 'Kiitenai na... Obāchan, Sora ga mata ue ni imasu.',
        english: "You're not listening... Grandma, Sora is up there again.",
      },
      {
        speaker: 'grandma',
        japanese: 'ほっときなさい。あの子は上が好きなんだよ。',
        segments: [
          { text: 'ほっときなさい。' },
          { text: 'あの' },
          { text: '子', reading: 'こ' },
          { text: 'は' },
          { text: '上', reading: 'うえ' },
          { text: 'が' },
          { text: '好', reading: 'す' },
          { text: 'きなんだよ。' },
        ],
        romaji: 'Hottokinasai. Ano ko wa ue ga suki nan da yo.',
        english: 'Just leave him. That one loves high places.',
      },
    ],
    newKanjiId: K.above,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s7,
    chapter: 1,
    order: 7,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'メガネが、ありません。',
        segments: [{ text: 'メガネが、' }, { text: 'ありません。' }],
        romaji: 'Megane ga, arimasen.',
        english: "I can't find my glasses.",
      },
      {
        speaker: 'grandma',
        japanese: '机の下は見たかい？下によく落ちてるんだよ。',
        segments: [
          { text: '机', reading: 'つくえ' },
          { text: 'の' },
          { text: '下', reading: 'した' },
          { text: 'は' },
          { text: '見', reading: 'み' },
          { text: 'たかい？' },
          { text: '下', reading: 'した' },
          { text: 'によく' },
          { text: '落', reading: 'お' },
          { text: 'ちてるんだよ。' },
        ],
        romaji: 'Tsukue no shita wa mita kai? Shita ni yoku ochiterun da yo.',
        english: "Did you look under the desk? They're often down there.",
      },
    ],
    newKanjiId: K.below,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s8,
    chapter: 1,
    order: 8,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        japanese: 'この箱の中は、何ですか？',
        segments: [
          { text: 'この' },
          { text: '箱', reading: 'はこ' },
          { text: 'の' },
          { text: '中', reading: 'なか' },
          { text: 'は、' },
          { text: '何', reading: 'なん' },
          { text: 'ですか？' },
        ],
        romaji: 'Kono hako no naka wa, nan desu ka?',
        english: "What's inside this box?",
      },
      {
        speaker: 'grandma',
        japanese: 'せんべいだよ。中のものは、好きに食べていいからね。',
        segments: [
          { text: 'せんべいだよ。' },
          { text: '中', reading: 'なか' },
          { text: 'のものは、' },
          { text: '好', reading: 'す' },
          { text: 'きに' },
          { text: '食', reading: 'た' },
          { text: 'べていいからね。' },
        ],
        romaji: 'Sembei da yo. Naka no mono wa, suki ni tabete ii kara ne.',
        english: 'Rice crackers. Feel free to eat anything inside.',
      },
    ],
    newKanjiId: K.inside,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s9,
    chapter: 1,
    order: 9,
    scene: '縁側',
    lines: [
      {
        speaker: 'grandma',
        japanese: 'ミアちゃん、ちょっと来てごらん。',
        segments: [
          { text: 'ミアちゃん、' },
          { text: 'ちょっと' },
          { text: '来', reading: 'き' },
          { text: 'てごらん。' },
        ],
        romaji: 'Mia-chan, chotto kite goran.',
        english: 'Mia, come here for a moment.',
      },
      {
        speaker: 'mia',
        japanese: 'わあ、星がきれいですね。',
        segments: [
          { text: 'わあ、' },
          { text: '星', reading: 'ほし' },
          { text: 'がきれいですね。' },
        ],
        romaji: 'Wā, hoshi ga kirei desu ne.',
        english: 'Wow, the stars are beautiful.',
      },
      {
        speaker: 'grandma',
        japanese: 'たまには、こうやって見るのもいいだろう？',
        segments: [
          { text: 'たまには、' },
          { text: 'こうやって' },
          { text: '見', reading: 'み' },
          { text: 'るのもいいだろう？' },
        ],
        romaji: 'Tama ni wa, kō yatte miru no mo ii darō?',
        english: "It's nice to look up like this once in a while, isn't it?",
      },
    ],
    newKanjiId: K.see,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s10,
    chapter: 1,
    order: 10,
    scene: '玄関',
    lines: [
      {
        speaker: 'mia',
        japanese: 'ただいま。',
        segments: [{ text: 'ただいま。' }],
        romaji: 'Tadaima.',
        english: "I'm home.",
      },
      {
        speaker: 'grandma',
        japanese: 'おかえり。この家にも、もう慣れたかい？',
        segments: [
          { text: 'おかえり。' },
          { text: 'この' },
          { text: '家', reading: 'いえ' },
          { text: 'にも、もう' },
          { text: '慣', reading: 'な' },
          { text: 'れたかい？' },
        ],
        romaji: 'Okaeri. Kono ie ni mo, mō nareta kai?',
        english: 'Welcome back. Are you getting used to this house?',
      },
      {
        speaker: 'mia',
        japanese: 'はい。家が、あたたかいです。',
        segments: [
          { text: 'はい。' },
          { text: '家', reading: 'いえ' },
          { text: 'が、あたたかいです。' },
        ],
        romaji: 'Hai. Ie ga, atatakai desu.',
        english: 'Yes. The house feels warm.',
      },
      {
        speaker: 'sora',
        japanese: 'ごはん。',
        segments: [{ text: 'ごはん。' }],
        romaji: 'Gohan.',
        english: 'Food.',
      },
      {
        speaker: 'mia',
        japanese: '……おかえりは？',
        segments: [{ text: '……おかえりは？' }],
        romaji: '...Okaeri wa?',
        english: "...What about 'welcome back'?",
      },
    ],
    newKanjiId: K.house,
    reencounters: [],
    isFree: true,
  },
  {
    id: S.s11,
    chapter: 2,
    order: 11,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        japanese: 'おはようございます。',
        segments: [{ text: 'おはようございます。' }],
        romaji: 'Ohayō gozaimasu.',
        english: 'Good morning.',
      },
      {
        speaker: 'grandma',
        japanese: 'おや、早いねえ。ごはんはまだだよ。',
        segments: [
          { text: 'おや、' },
          { text: '早', reading: 'はや' },
          { text: 'いねえ。' },
          { text: 'ごはんはまだだよ。' },
        ],
        romaji: 'Oya, hayai nē. Gohan wa mada da yo.',
        english: "My, you're up early. Breakfast isn't ready yet.",
      },
      {
        speaker: 'mia',
        japanese: '鳥の声で、目が覚めました。',
        segments: [
          { text: '鳥', reading: 'とり' },
          { text: 'の' },
          { text: '声', reading: 'こえ' },
          { text: 'で、' },
          { text: '目', reading: 'め' },
          { text: 'が' },
          { text: '覚', reading: 'さ' },
          { text: 'めました。' },
        ],
        romaji: 'Tori no koe de, me ga samemashita.',
        english: "The birds' voices woke me up.",
      },
      {
        speaker: 'grandma',
        japanese: 'あの子たちは、あたしより早いからねえ。',
        segments: [
          { text: 'あの' },
          { text: '子', reading: 'こ' },
          { text: 'たちは、あたしより' },
          { text: '早', reading: 'はや' },
          { text: 'いからねえ。' },
        ],
        romaji: 'Ano kotachi wa, atashi yori hayai kara nē.',
        english: 'The birds are up even earlier than me.',
      },
    ],
    newKanjiId: K.early,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s12,
    chapter: 2,
    order: 12,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'この時計は、古いですね。',
        segments: [
          { text: 'この' },
          { text: '時計', reading: 'とけい' },
          { text: 'は、' },
          { text: '古', reading: 'ふる' },
          { text: 'いですね。' },
        ],
        romaji: 'Kono tokei wa, furui desu ne.',
        english: 'This clock is old.',
      },
      {
        speaker: 'grandma',
        japanese: 'あたしが若い時からあるんだよ。',
        segments: [
          { text: 'あたしが' },
          { text: '若', reading: 'わか' },
          { text: 'い' },
          { text: '時', reading: 'とき' },
          { text: 'からあるんだよ。' },
        ],
        romaji: 'Atashi ga wakai toki kara arun da yo.',
        english: "It's been here since I was young.",
      },
    ],
    newKanjiId: K.time,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s13,
    chapter: 2,
    order: 13,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: '本と本の間に、何かありますね。',
        segments: [
          { text: '本', reading: 'ほん' },
          { text: 'と' },
          { text: '本', reading: 'ほん' },
          { text: 'の' },
          { text: '間', reading: 'あいだ' },
          { text: 'に、' },
          { text: '何', reading: 'なに' },
          { text: 'かありますね。' },
        ],
        romaji: 'Hon to hon no aida ni, nanika arimasu ne.',
        english: "There's something between the books.",
      },
      {
        speaker: 'grandma',
        japanese: 'ああ、写真ねえ。ずっとその間に入ってるんだよ。',
        segments: [
          { text: 'ああ、' },
          { text: '写真', reading: 'しゃしん' },
          { text: 'ねえ。' },
          { text: 'ずっとその' },
          { text: '間', reading: 'あいだ' },
          { text: 'に' },
          { text: '入', reading: 'はい' },
          { text: 'ってるんだよ。' },
        ],
        romaji: 'Ā, shashin nē. Zutto sono aida ni haitterun da yo.',
        english: "Ah, the photo. It's been sitting in there all this time.",
      },
    ],
    newKanjiId: K.interval,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s14,
    chapter: 2,
    order: 14,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: 'この言葉が、分かりません。',
        segments: [
          { text: 'この' },
          { text: '言葉', reading: 'ことば' },
          { text: 'が、' },
          { text: '分', reading: 'わ' },
          { text: 'かりません。' },
        ],
        romaji: 'Kono kotoba ga, wakarimasen.',
        english: "I don't understand this word.",
      },
      {
        speaker: 'grandma',
        japanese: 'どれどれ。……あたしも分からないねえ。',
        segments: [
          { text: 'どれどれ。……' },
          { text: 'あたしも' },
          { text: '分', reading: 'わ' },
          { text: 'からないねえ。' },
        ],
        romaji: 'Doredore... Atashi mo wakaranai nē.',
        english: "Let me see... I don't know it either.",
      },
    ],
    newKanjiId: K.understand,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s15,
    chapter: 2,
    order: 15,
    scene: '縁側',
    lines: [
      {
        speaker: 'mia',
        japanese: '今日の天気は、どうですか？',
        segments: [
          { text: '今日', reading: 'きょう' },
          { text: 'の' },
          { text: '天', reading: 'てん' },
          { text: '気', reading: 'き' },
          { text: 'は、どうですか？' },
        ],
        romaji: 'Kyō no tenki wa, dō desu ka?',
        english: "How's the weather today?",
      },
      {
        speaker: 'grandma',
        japanese: 'いい天気だねえ。でも、あとで雨だと天気予報が言ってたよ。',
        segments: [
          { text: 'いい' },
          { text: '天', reading: 'てん' },
          { text: '気', reading: 'き' },
          { text: 'だねえ。' },
          { text: 'でも、あとで' },
          { text: '雨', reading: 'あめ' },
          { text: 'だと' },
          { text: '天', reading: 'てん' },
          { text: '気', reading: 'き' },
          { text: '予報', reading: 'よほう' },
          { text: 'が' },
          { text: '言', reading: 'い' },
          { text: 'ってたよ。' },
        ],
        romaji: 'Ii tenki da nē. Demo, ato de ame da to tenkiyohō ga itteta yo.',
        english: "It's nice out. But the forecast said it'd rain later.",
      },
    ],
    newKanjiId: K.heaven,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s16,
    chapter: 2,
    order: 16,
    scene: '縁側',
    lines: [
      {
        speaker: 'mia',
        japanese: '本当に雨ですね。',
        segments: [
          { text: '本当', reading: 'ほんとう' },
          { text: 'に' },
          { text: '雨', reading: 'あめ' },
          { text: 'ですね。' },
        ],
        romaji: 'Hontō ni ame desu ne.',
        english: 'It really is raining.',
      },
      {
        speaker: 'grandma',
        japanese: '当たったねえ。雨の日は、家にいるのが一番だよ。',
        segments: [
          { text: '当', reading: 'あ' },
          { text: 'たったねえ。' },
          { text: '雨', reading: 'あめ' },
          { text: 'の' },
          { text: '日', reading: 'ひ' },
          { text: 'は、' },
          { text: '家', reading: 'いえ' },
          { text: 'にいるのが' },
          { text: '一番', reading: 'いちばん' },
          { text: 'だよ。' },
        ],
        romaji: 'Atatta nē. Ame no hi wa, ie ni iru no ga ichiban da yo.',
        english: 'It was right, after all. On rainy days, home is the best place.',
      },
      {
        speaker: 'mia',
        japanese: '空、雨だよ。今日は外に行けないね。',
        segments: [
          { text: '空', reading: 'そら' },
          { text: '、' },
          { text: '雨', reading: 'あめ' },
          { text: 'だよ。' },
          { text: '今日', reading: 'きょう' },
          { text: 'は' },
          { text: '外', reading: 'そと' },
          { text: 'に' },
          { text: '行', reading: 'い' },
          { text: 'けないね。' },
        ],
        romaji: 'Sora, ame da yo. Kyō wa soto ni ikenai ne.',
        english: "Sora, it's raining. We can't go outside today.",
      },
      {
        speaker: 'sora',
        japanese: 'ねむい。',
        segments: [{ text: 'ねむい。' }],
        romaji: 'Nemui.',
        english: 'Sleepy.',
      },
      {
        speaker: 'mia',
        japanese: 'いつもそれだね。',
        segments: [{ text: 'いつもそれだね。' }],
        romaji: 'Itsumo sore da ne.',
        english: "That's always your answer.",
      },
    ],
    newKanjiId: K.rain,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s17,
    chapter: 2,
    order: 17,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        // 「今日」を仮名で書いているのは、第2段階の演出で `日` を対象にすると
        // `今日` のセグメントも一緒に光り(toFuriganaSegments は includes 判定)、
        // 「ひ → にち/び」を見せたい回に4つ目の読み「きょう」が混ざるため。
        japanese: 'きょうは、何の日ですか？',
        segments: [
          { text: 'きょうは、' },
          { text: '何', reading: 'なん' },
          { text: 'の' },
          { text: '日', reading: 'ひ' },
          { text: 'ですか？' },
        ],
        romaji: 'Kyō wa, nan no hi desu ka?',
        english: 'What day is it today?',
      },
      {
        speaker: 'grandma',
        // 第2段階の演出行。`日` を1字ずつのセグメントに割ってあるのは、
        // 「にち」と「び」を字ごとに見せないと「同じ字なのに読みが違う」が成立しないため。
        // 語をまとめて {text:'日曜日', reading:'にちようび'} にすると演出が描けなくなる。
        japanese: '日曜日だよ。ゆっくりしなさい。',
        segments: [
          { text: '日', reading: 'にち' },
          { text: '曜', reading: 'よう' },
          { text: '日', reading: 'び' },
          { text: 'だよ。' },
          { text: 'ゆっくりしなさい。' },
        ],
        romaji: 'Nichiyōbi da yo. Yukkuri shinasai.',
        english: "It's Sunday. Take it easy.",
      },
      {
        speaker: 'mia',
        japanese: 'あ、同じ字なのに、読み方がちがう…！',
        segments: [
          { text: 'あ、' },
          { text: '同', reading: 'おな' },
          { text: 'じ' },
          { text: '字', reading: 'じ' },
          { text: 'なのに、' },
          { text: '読', reading: 'よ' },
          { text: 'み' },
          { text: '方', reading: 'かた' },
          { text: 'がちがう…！' },
        ],
        romaji: 'A, onaji ji na noni, yomikata ga chigau...!',
        english: 'The same character, but read differently...!',
      },
    ],
    // 第2章で唯一の第2段階専用の回。新出漢字は無い(決定事項 1章)
    newKanjiId: null,
    reencounters: [{ word: '日曜日', stage: 2, kanjiIds: [K.day] }],
    isFree: false,
  },
  {
    id: S.s18,
    chapter: 2,
    order: 18,
    scene: '縁側',
    lines: [
      {
        speaker: 'mia',
        japanese: '月が大きいですね。',
        segments: [
          { text: '月', reading: 'つき' },
          { text: 'が' },
          { text: '大', reading: 'おお' },
          { text: 'きいですね。' },
        ],
        romaji: 'Tsuki ga ōkii desu ne.',
        english: 'The moon is so big.',
      },
      {
        speaker: 'grandma',
        japanese: '今夜は満月だからねえ。',
        segments: [
          { text: '今夜', reading: 'こんや' },
          { text: 'は' },
          { text: '満', reading: 'まん' },
          { text: '月', reading: 'げつ' },
          { text: 'だからねえ。' },
        ],
        romaji: "Kon'ya wa mangetsu dakara nē.",
        english: "It's a full moon tonight.",
      },
    ],
    newKanjiId: K.moon,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s19,
    chapter: 2,
    order: 19,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        japanese: '水を、いただけますか？',
        segments: [{ text: '水', reading: 'みず' }, { text: 'を、いただけますか？' }],
        romaji: 'Mizu o, itadakemasu ka?',
        english: 'May I have some water?',
      },
      {
        speaker: 'grandma',
        japanese: 'どうぞ。冷たい水が、そこにあるよ。',
        segments: [
          { text: 'どうぞ。' },
          { text: '冷', reading: 'つめ' },
          { text: 'たい' },
          { text: '水', reading: 'みず' },
          { text: 'が、そこにあるよ。' },
        ],
        romaji: 'Dōzo. Tsumetai mizu ga, soko ni aru yo.',
        english: "Go ahead. There's cold water over there.",
      },
    ],
    newKanjiId: K.water,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s20,
    chapter: 2,
    order: 20,
    scene: '台所',
    lines: [
      {
        speaker: 'grandma',
        japanese: '火に気をつけてね。',
        segments: [
          { text: '火', reading: 'ひ' },
          { text: 'に' },
          { text: '気', reading: 'き' },
          { text: 'をつけてね。' },
        ],
        romaji: 'Hi ni ki o tsukete ne.',
        english: 'Be careful with the fire.',
      },
      {
        speaker: 'mia',
        japanese: 'はい。……「火」と「日」は、読み方が同じですね？',
        segments: [
          { text: 'はい。……「' },
          { text: '火', reading: 'ひ' },
          { text: '」と「' },
          { text: '日', reading: 'ひ' },
          { text: '」は、' },
          { text: '読', reading: 'よ' },
          { text: 'み' },
          { text: '方', reading: 'かた' },
          { text: 'が' },
          { text: '同', reading: 'おな' },
          { text: 'じですね？' },
        ],
        romaji: 'Hai... "hi" to "hi" wa, yomikata ga onaji desu ne?',
        english: "Yes. 火 and 日 are read the same way, aren't they?",
      },
      {
        speaker: 'grandma',
        japanese: 'よく気づいたねえ。形はちがうけど、どっちも「ひ」だよ。',
        segments: [
          { text: 'よく' },
          { text: '気', reading: 'き' },
          { text: 'づいたねえ。' },
          { text: '形', reading: 'かたち' },
          { text: 'はちがうけど、' },
          { text: 'どっちも「ひ」だよ。' },
        ],
        romaji: 'Yoku kizuita nē. Katachi wa chigau kedo, dotchi mo "hi" da yo.',
        english: "Good catch. Different shapes, but both are read 'hi'.",
      },
    ],
    newKanjiId: K.fire,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s21,
    chapter: 2,
    order: 21,
    scene: '庭',
    lines: [
      {
        speaker: 'mia',
        japanese: '大きい木ですね。',
        segments: [
          { text: '大', reading: 'おお' },
          { text: 'きい' },
          { text: '木', reading: 'き' },
          { text: 'ですね。' },
        ],
        romaji: 'Ōkii ki desu ne.',
        english: "That's a big tree.",
      },
      {
        speaker: 'grandma',
        japanese: 'あたしより年上だよ、この木は。',
        segments: [
          { text: 'あたしより' },
          { text: '年上', reading: 'としうえ' },
          { text: 'だよ、この' },
          { text: '木', reading: 'き' },
          { text: 'は。' },
        ],
        romaji: 'Atashi yori toshiue da yo, kono ki wa.',
        english: 'This tree is older than me.',
      },
      {
        speaker: 'mia',
        japanese: 'あっ、空。そこは高いよ。',
        segments: [
          { text: 'あっ、' },
          { text: '空', reading: 'そら' },
          { text: '。そこは' },
          { text: '高', reading: 'たか' },
          { text: 'いよ。' },
        ],
        romaji: 'A, Sora. Soko wa takai yo.',
        english: "Oh, Sora. That's high up.",
      },
      {
        // 空の語彙に位置の語を入れる回。決定事項 3章の「存在」にあたり、
        // 第1章 #6「あの子は上が好きなんだよ」の回収も兼ねる
        speaker: 'sora',
        japanese: '上。',
        segments: [{ text: '上', reading: 'うえ' }, { text: '。' }],
        romaji: 'Ue.',
        english: 'Up.',
      },
    ],
    newKanjiId: K.tree,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s22,
    chapter: 2,
    order: 22,
    scene: '玄関',
    lines: [
      {
        speaker: 'mia',
        japanese: 'お金を、忘れました。',
        segments: [
          { text: 'お' },
          { text: '金', reading: 'かね' },
          { text: 'を、' },
          { text: '忘', reading: 'わす' },
          { text: 'れました。' },
        ],
        romaji: 'Okane o, wasuremashita.',
        english: 'I forgot my money.',
      },
      {
        speaker: 'grandma',
        japanese: 'あらあら。お金がないと、こまるねえ。',
        segments: [
          { text: 'あらあら。' },
          { text: 'お' },
          { text: '金', reading: 'かね' },
          { text: 'がないと、' },
          { text: 'こまるねえ。' },
        ],
        romaji: 'Ara ara. Okane ga nai to, komaru nē.',
        english: "Oh dear. You'll be stuck without money.",
      },
    ],
    newKanjiId: K.money,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s23,
    chapter: 2,
    order: 23,
    scene: '庭',
    lines: [
      {
        speaker: 'grandma',
        japanese: 'この土は、いい土なんだよ。',
        segments: [
          { text: 'この' },
          { text: '土', reading: 'つち' },
          { text: 'は、いい' },
          { text: '土', reading: 'つち' },
          { text: 'なんだよ。' },
        ],
        romaji: 'Kono tsuchi wa, ii tsuchi nan da yo.',
        english: 'This soil is good soil.',
      },
      {
        speaker: 'mia',
        japanese: '花が、たくさん咲いていますね。',
        segments: [
          { text: '花', reading: 'はな' },
          { text: 'が、たくさん' },
          { text: '咲', reading: 'さ' },
          { text: 'いていますね。' },
        ],
        romaji: 'Hana ga, takusan saite imasu ne.',
        english: 'There are so many flowers blooming.',
      },
    ],
    newKanjiId: K.soil,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s24,
    chapter: 2,
    order: 24,
    scene: '居間',
    lines: [
      {
        speaker: 'mia',
        japanese: '少し、休みます。',
        segments: [
          { text: '少', reading: 'すこ' },
          { text: 'し、' },
          { text: '休', reading: 'やす' },
          { text: 'みます。' },
        ],
        romaji: 'Sukoshi, yasumimasu.',
        english: "I'm going to rest for a bit.",
      },
      {
        speaker: 'grandma',
        japanese: 'そうしなさい。あたしも少し休もうかねえ。',
        segments: [
          { text: 'そうしなさい。' },
          { text: 'あたしも' },
          { text: '少', reading: 'すこ' },
          { text: 'し' },
          { text: '休', reading: 'やす' },
          { text: 'もうかねえ。' },
        ],
        romaji: 'Sō shinasai. Atashi mo sukoshi yasumō ka nē.',
        english: "You should. I think I'll rest a bit myself.",
      },
      {
        speaker: 'mia',
        japanese: '空、いっしょに休もう。',
        segments: [
          { text: '空', reading: 'そら' },
          { text: '、いっしょに' },
          { text: '休', reading: 'やす' },
          { text: 'もう。' },
        ],
        romaji: 'Sora, issho ni yasumō.',
        english: "Sora, let's rest together.",
      },
      {
        speaker: 'sora',
        japanese: 'ねむい。',
        segments: [{ text: 'ねむい。' }],
        romaji: 'Nemui.',
        english: 'Sleepy.',
      },
      {
        speaker: 'mia',
        japanese: '今日はぴったりだね。',
        segments: [{ text: '今日', reading: 'きょう' }, { text: 'はぴったりだね。' }],
        romaji: 'Kyō wa pittari da ne.',
        english: 'That fits perfectly today.',
      },
    ],
    newKanjiId: K.rest,
    reencounters: [],
    isFree: false,
  },
  {
    id: S.s25,
    chapter: 2,
    order: 25,
    scene: '台所',
    lines: [
      {
        speaker: 'mia',
        japanese: 'おばあちゃん、少し話してもいいですか？',
        segments: [
          { text: 'おばあちゃん、' },
          { text: '少', reading: 'すこ' },
          { text: 'し' },
          { text: '話', reading: 'はな' },
          { text: 'してもいいですか？' },
        ],
        romaji: 'Obāchan, sukoshi hanashite mo ii desu ka?',
        english: 'Grandma, may I talk with you for a bit?',
      },
      {
        speaker: 'grandma',
        japanese: 'いいよ。何でも話しなさい。',
        segments: [
          { text: 'いいよ。' },
          { text: '何', reading: 'なん' },
          { text: 'でも' },
          { text: '話', reading: 'はな' },
          { text: 'しなさい。' },
        ],
        romaji: 'Ii yo. Nandemo hanashinasai.',
        english: 'Of course. Tell me anything.',
      },
    ],
    newKanjiId: K.speak,
    reencounters: [],
    isFree: false,
  },
];

export const contentSet: ContentSet = { kanji, words, sentences };
